config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :orders
  resources :courses
  resources :emailcourses
  resources :webs
  resources :contacts
  resources :expertleads
  resources :newsletters
  resources :facebookads
  resources :projecttypes
  
  resources :costs
  resources :projects do
   resources :timelines
  end
  resources :photos
  resources :potentials
  resources :legends
  resources :clients
  resources :sections
  resources :articles
  resources :leads
  devise_for :users
  resources :users, :only => [:show, :index]
  resources :dreams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "articles#index"
  match 'helpbusinessesgrow', to: 'static_pages#helpbusinessesgrow', via: 'get'
  match 'homebig', to: 'static_pages#homebig', via: 'get'
  match 'home', to: 'static_pages#home', via: 'get'
  match 'websites', to: 'static_pages#websites', via: 'get'
  match 'digitalmarketing', to: 'static_pages#digitalmarketing', via: 'get'
  match 'seo', to: 'static_pages#seo', via: 'get'
  match 'socialandemailmarketing', to: 'static_pages#socialandemailmarketing', via: 'get'
  match 'aboutus', to: 'static_pages#aboutus', via: 'get'
  match 'helpghanaianbusinessesleads', to: 'static_pages#helpghanaianbusinessesleads', via: 'get'
  match 'thankyoulead', to: 'static_pages#thankyoulead', via: 'get'
  match 'ourservices', to: 'static_pages#ourservices', via: 'get'
  match 'dashboard', to: 'static_pages#dashboard', via: 'get'
  match 'fbadvertisementsleads', to: 'static_pages#fbadvertisementsleads', via: 'get'
  match 'learninternetmarketing', to: 'static_pages#learninternetmarketing', via: 'get'
  match 'buy_first_1', to: 'static_pages#buy_first_1', via: 'get'
  match 'thankyouhbo', to: 'static_pages#thankyouhbo', via: 'get'
  match 'landbyknowing', to: 'static_pages#landbyknowing', via: 'get'
  match 'homeadappointment', to: 'static_pages#homeadappointment', via: 'get'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ApplicationRecord
	  resourcify
	  extend FriendlyId
      friendly_id :title, use: :slugged
      has_many :photos
	  mount_uploader :articleimage, ArticleimageUploader
	  has_many :sectors
	  has_many :sections, through: :sectors
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
	resourcify
end

app/models/cost.rb
class Cost < ApplicationRecord
	belongs_to :project
	resourcify

def day
  self.created_at.strftime("%D")
end

def week
  self.created_at.strftime("%W")
end

end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/dream.rb
class Dream < ApplicationRecord
	resourcify
end

app/models/lead.rb
class Lead < ApplicationRecord
	resourcify
end

app/models/legend.rb
class Legend < ApplicationRecord
	resourcify
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
	attachment :article_image
	belongs_to :article
end

app/models/potential.rb
class Potential < ApplicationRecord
	resourcify
end

app/models/project.rb
class Project < ApplicationRecord
	resourcify
	has_many :costs
	has_many :timelines
	has_many :userprojects, :dependent => :destroy, :autosave => true
    has_many :users, through: :userprojects
    has_many :protypes, :dependent => :destroy, :autosave => true
    has_many :projecttypes, through: :protypes
    accepts_nested_attributes_for :costs, :allow_destroy => true
    default_scope -> { order('created_at DESC') }
end

app/models/protype.rb
class Protype < ApplicationRecord
	belongs_to :project
	belongs_to :projecttype
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/section.rb
class Section < ApplicationRecord
	resourcify
	extend FriendlyId
    friendly_id :name, use: :slugged
	mount_uploader :sectionimage, SectionimageUploader
	has_many :sectors
	has_many :articles, through: :sectors
end

app/models/sector.rb
class Sector < ApplicationRecord
	belongs_to :article
	belongs_to :section
end

app/models/timeline.rb
class Timeline < ApplicationRecord
	resourcify
	belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  after_create :send_admin_mail
  has_many :userprojects, :dependent => :destroy, :autosave => true
  has_many :projects, through: :userprojects

     
  def send_admin_mail
    RegistrationMailer.register_message(self).deliver
  end

end

app/models/web.rb
class Web < ApplicationRecord
	resourcify
end

app/views/webs/_form.html.erb
<style type="text/css">
  /* -- import Bootstrap v3 --------------------------- */
/* -- import Bootstrap docs ------------------------- */
/* -- import Roboto Font ---------------------------- */
@import "https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic&subset=latin,cyrillic";
/* -- Body style ------------------------------------ */

/* -- Input styles ---------------------------------- */
.form-group {
  position: relative;
  margin-top: 35px;
  margin-bottom: 20px;
}
.input-group {
  position: relative;
}
.form-control {
  display: block;
  height: 36px;
  width: 100%; 
  border: none;
  border-radius: 0 !important;

  font-size: 16px;
  font-weight: 300;
  padding: 0;
  background-color: transparent;
  box-shadow: none;
  border-bottom: 1px solid #757575;
}
.input-group .form-control {
  position: relative;
  z-index: inherit;
  float: inherit;
  width: 100%;
  margin-bottom: 0;
}
.form-control:focus {
  border-color: #757575;
  outline: none;
  box-shadow: none;
}

/* -- label styles ---------------------------------- */
label {
  position: absolute;
  top: -18px;
  color: #999;
  font-size: 12px;
  font-weight: 300;
  
  transition: 0.2s ease all;
  -moz-transition: 0.2s ease all;
  -webkit-transition: 0.2s ease all;
}

.form-horizontal .control-label {
  position: relative;
  top: 0;
  margin-bottom: 0;
}

@media (min-width: 768px) {
  .form-horizontal .control-label {
    font-size: 16px;
  }
}
  




.float-label {
  left: 0;
  top: 7px;
  font-size: 16px;
  pointer-events: none;
}

/* active state */
.form-control:focus ~ .float-label, .form-control:valid ~ .float-label {
  top: -18px;
  font-size: 12px;
}


/* input colors ---- */
// default
.form-control:focus {
  ~ label {
    color: #03a9f4;
  }
  
  ~ .form-bar:before, ~ .form-bar:after {
    background: #03a9f4;
  }
}




.form-control:valid ~ .control-label {

}

/* help-block */
.form-group .help-block {
  position: absolute;
}

.help-block {
  color: #bdbdbd; // caption
  font-size: 12px;
  font-weight: 300;
}

/* input addon ---*/
.input-group-addon {
  border: none;
  background: transparent;
}

/* ------  inline ----*/
.input-group-addon, .form-inline .input-group {
  display: table-cell;
}

.input-group-addon, .input-group-btn {
  width: inherit;
}

.input-group {
  width: 100%;
}

@media (min-width: 768px) {
  .form-inline .form-group {
    margin-top: 16px;
  }
  
  .input-group-btn, .input-group .form-control, .input-group-addon, .form-inline .input-group {
    display: inline-block;
  }
  
  .input-group {
    width: auto;
  }
}

/* -- bar styles -------------------------------------- */
.form-bar {
  position: relative;
  display: block;
  width: 100%;
}
.form-bar:before, .form-bar:after   {
  content: '';
  height: 1px;
  width: 0;
  bottom: 0;
  position: absolute;
  transition: 0.3s ease all;
  -moz-transition: 0.3s ease all;
  -webkit-transition: 0.3s ease all;
}
.form-bar:before {
  left: 50%;
}
.form-bar:after {
  right: 50%;
}

/* active state */
.form-control:focus ~ .form-bar:before, .form-control:focus ~ .form-bar:after {
  width: 50%;
}

/* -- highlighter styles ------------------------------ */
.form-highlight {
  position: absolute;
  height: 60%;
  width: 60px;
  top: 25%;
  left: 0;
  pointer-events: none;
  opacity: 0.4;
}

/* active state */
.form-control:focus ~ .form-highlight {
  -webkit-animation: inputHighlighter 0.3s ease;
  -moz-animation: inputHighlighter 0.3s ease;
  animation: inputHighlighter 0.3s ease;
}

/* -- highlighter animation --------------------------- */
@-webkit-keyframes inputHighlighter {
  from { background:#5264AE; }
  to { width:0; background:transparent; }
}
@-moz-keyframes inputHighlighter {
  from { background:#5264AE; }
  to { width:0; background:transparent; }
}
@keyframes inputHighlighter {
  from { background:#5264AE; }
  to { width:0; background:transparent; }
}


/*-- Checkbox --------------------------- */
// fork from https://codepen.io/jasonmayes/pen/wxtFr
/* 
 * Core styles required for the checkboxes.
 * @author Jason Mayes 2014, www.jasonmayes.com
*/
.form-group.checkbox {
  margin-top: 20px;
}

.checkbox input[type='checkbox'] {
  height: 0;
  width: 0;
  opacity: 0;
}

.checkbox label {
  font-size: 14px;
  font-weight: 300;
  line-height: 1;
  display: inline-block;
  overflow: hidden;
  position: relative;
  top: 10px;
  padding-left: 0;
}

.checkbox .chk-span {
  top: 0;
  border: 1px solid #5a5a5a;
  color: #1d1d1d;
  cursor: pointer;
  display: inline-block;
  float: left;
  height: 14px;
  margin: 0 14px 14px 1px;
  outline-color: #eaeaea;
  padding: 0;
  position: relative;
  width: 14px;
  -webkit-transition: all 0.2s ease-in-out;
  -moz-transition: all 0.2s ease-in-out;
  transition: all 0.2s ease-in-out;
  z-index: 1;
}

.checkbox .chk-span.checked {
  top: -2px;
  border-left: 2px solid #03a9f4;
  border-bottom: 4px solid #03a9f4;
  border-top: 1px solid rgba(0,0,0,0);
  border-right: 1px solid rgba(0,0,0,0);
  -webkit-transform: rotate(-45deg) scaleY(0.5);
  -moz-transform: rotate(-45deg) scaleY(0.5);
  -ms-transform: rotate(-45deg) scaleY(0.5);
  -o-transform: rotate(-45deg) scaleY(0.5);
  transform: rotate(-45deg) scaleY(0.5);
}

// Checkbox colors
.checkbox .chk-span.checked {
  border-left-color: #03a9f4;
  border-bottom-color: #03a9f4;
}

// focus state
.checkbox input[type='checkbox']:focus ~ label {
  
  color: #03a9f4;
  
  .chk-span {
    border-color: #03a9f4;
    &.checked {
      border-left-color: #03a9f4;
      border-bottom-color: #03a9f4;
      border-top: 1px solid rgba(0, 0, 0, 0);
      border-right: 1px solid rgba(0, 0, 0, 0);
    }
  }
}



@media (min-width: 768px) {
  .form-inline .radio label, .form-inline .checkbox label {
    padding-left: 5px;
  }
}





.form-control-static {
  font-size: 16px;
}

.form-control[disabled], .form-control[readonly], fieldset[disabled] .form-control {
  background-color: transparent;
  border-bottom-style: dashed;
}














#focusedInput {
  border-color: #ccc;
  border-color: rgba(82,168,236,.8);
  outline: 0;
  box-shadow: none;
}

.famcolorer{
  background-color: #5cc804;
  color: white;
  border: 1px solid #5cc804;
  padding: 20px;
}

.famcolorer:hover{
  background-color: #fdca00;
  color: white;
  border: 2px solid #5cc804;
}

.famcolorer:active{
  background-color: #fdca00;
  color: white;
  border: 1px solid #5cc804;
}
</style>

<script type="text/javascript">
  /*
 * Material Deesign Checkboxes non Polymer updated for use in bootstrap.
 * Tested and working in: IE9+, Chrome (Mobile + Desktop), Safari, Opera, Firefox.
 * @author Jason Mayes 2014, www.jasonmayes.com
 * @update Sergey Kupletsky 2014, www.design4net.ru
*/

var wskCheckbox = function() {
  var wskCheckboxes = [];
  var SPACE_KEY = 32;

  function addEventHandler(elem, eventType, handler) {
    if (elem.addEventListener) {
      elem.addEventListener (eventType, handler, false);
    }
    else if (elem.attachEvent) {
      elem.attachEvent ('on' + eventType, handler);
    }
  }

  function clickHandler(e) {
    e.stopPropagation();
    if (this.className.indexOf('checked') < 0) {
      this.className += ' checked';
    } else {
      this.className = 'chk-span';
    }
  }

  function keyHandler(e) {
    e.stopPropagation();
    if (e.keyCode === SPACE_KEY) {
      clickHandler.call(this, e);
      // Also update the checkbox state.

      var cbox = document.getElementById(this.parentNode.getAttribute('for'));
      cbox.checked = !cbox.checked;
    }
  }

  function clickHandlerLabel(e) {
    var id = this.getAttribute('for');
    var i = wskCheckboxes.length;
    while (i--) {
      if (wskCheckboxes[i].id === id) {
        if (wskCheckboxes[i].checkbox.className.indexOf('checked') < 0) {
          wskCheckboxes[i].checkbox.className += ' checked';
        } else {
          wskCheckboxes[i].checkbox.className = 'chk-span';
        }
        break;
      }
    }
  }

  function findCheckBoxes() {
    var labels =  document.getElementsByTagName('label');
    var i = labels.length;
    while (i--) {
      var posCheckbox = document.getElementById(labels[i].getAttribute('for'));
      if (posCheckbox !== null && posCheckbox.type === 'checkbox') {
        var text = labels[i].innerText;
        var span = document.createElement('span');
        span.className = 'chk-span';
        span.tabIndex = i;
        labels[i].insertBefore(span, labels[i].firstChild);
        addEventHandler(span, 'click', clickHandler);
        addEventHandler(span, 'keyup', keyHandler);
        addEventHandler(labels[i], 'click', clickHandlerLabel);
        wskCheckboxes.push({'checkbox': span,
            'id': labels[i].getAttribute('for')});
      }
    }
  }

  return {
    init: findCheckBoxes
  };
}();

wskCheckbox.init();
</script>


<%= form_for(web) do |f| %>
  <% if web.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(web.errors.count, "error") %> prohibited this web from being saved:</h2>

      <ul>
      <% web.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h3 style="color: #5cc804; font-weight: 700; text-align: center;">ABOUT YOU</h3>
<br>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control", :placeholder => "Your Name" %>
  </div>
  <br>
<div class="form-row">
  <div class="col-lg-6 col-sm-12">
    <%= f.label :email %>
    <%= f.text_field :email, :class => "form-control", :placeholder => "Your Email" %>
  </div>

  <div class="col-lg-6 col-sm-12">
    <%= f.label :phone %>
    <%= f.text_field :phone, :class => "form-control", :placeholder => "Your Phone Number" %>
  </div>
</div>
<br>
  <div class="form-group">
    <label>About Company</label>
    <%= f.text_area :aboutcompany, :class => "form-control", :placeholder => "Tell us About Your Company" %>
  </div>
  <br><br><br>
  <h3 style="color: #5cc804; font-weight: 700; text-align: center;">ABOUT YOUR PROJECT</h3>
  <br><br>
  <div class="form-group">
    <label>About Project</label>
    <%= f.text_area :aboutproject, :class => "form-control", :placeholder => "Tell us About Your Project" %>
  </div>
<br>
  <div class="form-group">
    <label>Project Deadline</label>
    <%= f.text_area :projectdeadline, :class => "form-control", :placeholder => "Tell us your deadline" %>
  </div>
<br>
  <div class="form-group">
    <label>Budget Allocated</label>
    <%= f.text_field :projectbudget, :class => "form-control", :placeholder => "Tell us About Your Budget Allocated" %>
  </div>
<br>
  <div class="form-group">
   <label>Target Market</label>
    <%= f.text_field :targetaudience, :class => "form-control" , :placeholder => "Tell us your target market group" %>
  </div>

  <div class="form-group">
   <p style="text-align: center;"> <%= f.submit "Let's Start Working Together", :class => "btn btn-success btn-lg famcolorer" %></p>
  </div>
<% end %>

app/views/webs/edit.html.erb
<h1>Editing Web</h1>

<%= render 'form', web: @web %>

<%= link_to 'Show', @web %> |
<%= link_to 'Back', webs_path %>

app/views/webs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Webs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Aboutcompany</th>
      <th>Aboutproject</th>
      <th>Projectdeadline</th>
      <th>Projectbudget</th>
      <th>Targetaudience</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @webs.each do |web| %>
      <tr>
        <td><%= web.name %></td>
        <td><%= web.email %></td>
        <td><%= web.phone %></td>
        <td><%= web.aboutcompany %></td>
        <td><%= web.aboutproject %></td>
        <td><%= web.projectdeadline %></td>
        <td><%= web.projectbudget %></td>
        <td><%= web.targetaudience %></td>
        <td><%= link_to 'Show', web %></td>
        <td><%= link_to 'Edit', edit_web_path(web) %></td>
        <td><%= link_to 'Destroy', web, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Web', new_web_path %>

app/views/webs/new.html.erb
<style type="text/css">
	
.letsworkhead{
	text-align: center;
	font-size: 70px;
	font-weight: 700;
	color: #5cc804;
	font-family: 'Poppins', sans-serif;
}

.letsworksub{
	font-weight: 300;
	font-size: 22px;
	text-align: center;
	color: #6c6c6d;
	font-family: 'Poppins', sans-serif;
}

</style>


<body style="background-color: #ffffff;">

<br><br><br><br>

<h1 class="letsworkhead">let's Work!</h1>
<br><br>
<p class="letsworksub">Let's get to work on your website. Please answer a couple of short questions <br>about you and your project.</p><br><br><br>
<div class="container">
	<div class="row">
       <div class="col-sm-12">
<%= render 'form', web: @web %>
       </div>
   </div>
</div>
<br>
<br>
<br>

</body>

app/views/webs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @web.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @web.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @web.phone %>
</p>

<p>
  <strong>Aboutcompany:</strong>
  <%= @web.aboutcompany %>
</p>

<p>
  <strong>Aboutproject:</strong>
  <%= @web.aboutproject %>
</p>

<p>
  <strong>Projectdeadline:</strong>
  <%= @web.projectdeadline %>
</p>

<p>
  <strong>Projectbudget:</strong>
  <%= @web.projectbudget %>
</p>

<p>
  <strong>Targetaudience:</strong>
  <%= @web.targetaudience %>
</p>

<%= link_to 'Edit', edit_web_path(@web) %> |
<%= link_to 'Back', webs_path %>