config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :orders
  resources :courses
  resources :emailcourses
  resources :webs
  resources :contacts
  resources :expertleads
  resources :newsletters
  resources :facebookads
  resources :projecttypes
  
  resources :costs
  resources :projects do
   resources :timelines
  end
  resources :photos
  resources :potentials
  resources :legends
  resources :clients
  resources :sections
  resources :articles
  resources :leads
  devise_for :users
  resources :users, :only => [:show, :index]
  resources :dreams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "articles#index"
  match 'helpbusinessesgrow', to: 'static_pages#helpbusinessesgrow', via: 'get'
  match 'homebig', to: 'static_pages#homebig', via: 'get'
  match 'home', to: 'static_pages#home', via: 'get'
  match 'websites', to: 'static_pages#websites', via: 'get'
  match 'digitalmarketing', to: 'static_pages#digitalmarketing', via: 'get'
  match 'seo', to: 'static_pages#seo', via: 'get'
  match 'socialandemailmarketing', to: 'static_pages#socialandemailmarketing', via: 'get'
  match 'aboutus', to: 'static_pages#aboutus', via: 'get'
  match 'helpghanaianbusinessesleads', to: 'static_pages#helpghanaianbusinessesleads', via: 'get'
  match 'thankyoulead', to: 'static_pages#thankyoulead', via: 'get'
  match 'ourservices', to: 'static_pages#ourservices', via: 'get'
  match 'dashboard', to: 'static_pages#dashboard', via: 'get'
  match 'fbadvertisementsleads', to: 'static_pages#fbadvertisementsleads', via: 'get'
  match 'learninternetmarketing', to: 'static_pages#learninternetmarketing', via: 'get'
  match 'buy_first_1', to: 'static_pages#buy_first_1', via: 'get'
  match 'thankyouhbo', to: 'static_pages#thankyouhbo', via: 'get'
  match 'landbyknowing', to: 'static_pages#landbyknowing', via: 'get'
  match 'homeadappointment', to: 'static_pages#homeadappointment', via: 'get'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ApplicationRecord
	  resourcify
	  extend FriendlyId
      friendly_id :title, use: :slugged
      has_many :photos
	  mount_uploader :articleimage, ArticleimageUploader
	  has_many :sectors
	  has_many :sections, through: :sectors
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
	resourcify
end

app/models/cost.rb
class Cost < ApplicationRecord
	belongs_to :project
	resourcify

def day
  self.created_at.strftime("%D")
end

def week
  self.created_at.strftime("%W")
end

end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/dream.rb
class Dream < ApplicationRecord
	resourcify
end

app/models/facebookad.rb
class Facebookad < ApplicationRecord
	resourcify
end

app/models/lead.rb
class Lead < ApplicationRecord
	resourcify
end

app/models/legend.rb
class Legend < ApplicationRecord
	resourcify
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
	attachment :article_image
	belongs_to :article
end

app/models/potential.rb
class Potential < ApplicationRecord
	resourcify
end

app/models/project.rb
class Project < ApplicationRecord
	resourcify
	has_many :costs
	has_many :timelines
	has_many :userprojects, :dependent => :destroy, :autosave => true
    has_many :users, through: :userprojects
    has_many :protypes, :dependent => :destroy, :autosave => true
    has_many :projecttypes, through: :protypes
    accepts_nested_attributes_for :costs, :allow_destroy => true
    default_scope -> { order('created_at DESC') }
end

app/models/protype.rb
class Protype < ApplicationRecord
	belongs_to :project
	belongs_to :projecttype
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/section.rb
class Section < ApplicationRecord
	resourcify
	extend FriendlyId
    friendly_id :name, use: :slugged
	mount_uploader :sectionimage, SectionimageUploader
	has_many :sectors
	has_many :articles, through: :sectors
end

app/models/sector.rb
class Sector < ApplicationRecord
	belongs_to :article
	belongs_to :section
end

app/models/timeline.rb
class Timeline < ApplicationRecord
	resourcify
	belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  after_create :send_admin_mail
  has_many :userprojects, :dependent => :destroy, :autosave => true
  has_many :projects, through: :userprojects

     
  def send_admin_mail
    RegistrationMailer.register_message(self).deliver
  end

end

app/models/web.rb
class Web < ApplicationRecord
	resourcify
end

app/controllers/facebookads_controller.rb
class FacebookadsController < ApplicationController
  before_action :set_facebookad, only: [:show, :edit, :update, :destroy]

  # GET /facebookads
  # GET /facebookads.json
  def index
    @facebookads = Facebookad.all
  end

  # GET /facebookads/1
  # GET /facebookads/1.json
  def show
  end

  # GET /facebookads/new
  def new
    @facebookad = Facebookad.new
  end

  # GET /facebookads/1/edit
  def edit
  end

  # POST /facebookads
  # POST /facebookads.json
  def create
    @facebookad = Facebookad.new(facebookad_params)

    respond_to do |format|
      if @facebookad.save
        format.html { redirect_to @facebookad, notice: 'Facebookad was successfully created.' }
        format.json { render :show, status: :created, location: @facebookad }
      else
        format.html { render :new }
        format.json { render json: @facebookad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facebookads/1
  # PATCH/PUT /facebookads/1.json
  def update
    respond_to do |format|
      if @facebookad.update(facebookad_params)
        format.html { redirect_to @facebookad, notice: 'Facebookad was successfully updated.' }
        format.json { render :show, status: :ok, location: @facebookad }
      else
        format.html { render :edit }
        format.json { render json: @facebookad.errors, status: :unprocessable_entity }
      end
    end
    authorize! :update, @facebookad
  end

  # DELETE /facebookads/1
  # DELETE /facebookads/1.json
  def destroy
    @facebookad.destroy
    respond_to do |format|
      format.html { redirect_to facebookads_url, notice: 'Facebookad was successfully destroyed.' }
      format.json { head :no_content }
    end
    authorize! :destroy, @facebookad
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facebookad
      @facebookad = Facebookad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facebookad_params
      params[:facebookad][:resultsywant] = params[:facebookad][:resultsywant].join(',')
      params.require(:facebookad).permit(:resultsywant, :budget, :name, :email, :phonenumber)
    end
end

app/helpers/facebookads_helper.rb
module FacebookadsHelper
end

app/views/facebookads/_form.html.erb
<%= form_for(facebookad) do |f| %>
  <% if facebookad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(facebookad.errors.count, "error") %> prohibited this facebookad from being saved:</h2>

      <ul>
      <% facebookad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :resultsywant %>
    <%= f.text_field :resultsywant %>
  </div>

  <div class="field">
    <%= f.label :budget %>
    <%= f.text_field :budget %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phonenumber %>
    <%= f.text_field :phonenumber %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facebookads/edit.html.erb
<h1>Editing Facebookad</h1>

<%= render 'form', facebookad: @facebookad %>

<%= link_to 'Show', @facebookad %> |
<%= link_to 'Back', facebookads_path %>

app/views/facebookads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Facebookads</h1>

<table>
  <thead>
    <tr>
      <th>Resultsywant</th>
      <th>Budget</th>
      <th>Name</th>
      <th>Email</th>
      <th>Phonenumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @facebookads.each do |facebookad| %>
      <tr>
        <td><%= facebookad.resultsywant %></td>
        <td><%= facebookad.budget %></td>
        <td><%= facebookad.name %></td>
        <td><%= facebookad.email %></td>
        <td><%= facebookad.phonenumber %></td>
        <td><%= link_to 'Show', facebookad %></td>
        <td><%= link_to 'Edit', edit_facebookad_path(facebookad) %></td>
        <td><%= link_to 'Destroy', facebookad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Facebookad', new_facebookad_path %>

app/views/facebookads/new.html.erb
<h1>New Facebookad</h1>

<%= render 'form', facebookad: @facebookad %>

<%= link_to 'Back', facebookads_path %>

app/views/facebookads/show.html.erb
<br><br><br><br>

<p id="notice"><%= notice %></p>

<p>
  <strong>Results you want:</strong>
  <%= @facebookad.resultsywant %>
</p>

<p>
  <strong>Budget Allocation:</strong>
  <%= @facebookad.budget %>
</p>

<p>
  <strong>Name:</strong>
  <%= @facebookad.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @facebookad.email %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @facebookad.phonenumber %>
</p>

<%= link_to 'Edit', edit_facebookad_path(@facebookad) %> |
<%= link_to 'Back', facebookads_path %>

<br><br>