config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :orders
  resources :courses
  resources :emailcourses
  resources :webs
  resources :contacts
  resources :expertleads
  resources :newsletters
  resources :facebookads
  resources :projecttypes
  
  resources :costs
  resources :projects do
   resources :timelines
  end
  resources :photos
  resources :potentials
  resources :legends
  resources :clients
  resources :sections
  resources :articles
  resources :leads
  devise_for :users
  resources :users, :only => [:show, :index]
  resources :dreams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "articles#index"
  match 'helpbusinessesgrow', to: 'static_pages#helpbusinessesgrow', via: 'get'
  match 'homebig', to: 'static_pages#homebig', via: 'get'
  match 'home', to: 'static_pages#home', via: 'get'
  match 'websites', to: 'static_pages#websites', via: 'get'
  match 'digitalmarketing', to: 'static_pages#digitalmarketing', via: 'get'
  match 'seo', to: 'static_pages#seo', via: 'get'
  match 'socialandemailmarketing', to: 'static_pages#socialandemailmarketing', via: 'get'
  match 'aboutus', to: 'static_pages#aboutus', via: 'get'
  match 'helpghanaianbusinessesleads', to: 'static_pages#helpghanaianbusinessesleads', via: 'get'
  match 'thankyoulead', to: 'static_pages#thankyoulead', via: 'get'
  match 'ourservices', to: 'static_pages#ourservices', via: 'get'
  match 'dashboard', to: 'static_pages#dashboard', via: 'get'
  match 'fbadvertisementsleads', to: 'static_pages#fbadvertisementsleads', via: 'get'
  match 'learninternetmarketing', to: 'static_pages#learninternetmarketing', via: 'get'
  match 'buy_first_1', to: 'static_pages#buy_first_1', via: 'get'
  match 'thankyouhbo', to: 'static_pages#thankyouhbo', via: 'get'
  match 'landbyknowing', to: 'static_pages#landbyknowing', via: 'get'
  match 'homeadappointment', to: 'static_pages#homeadappointment', via: 'get'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ApplicationRecord
	  resourcify
	  extend FriendlyId
      friendly_id :title, use: :slugged
      has_many :photos
	  mount_uploader :articleimage, ArticleimageUploader
	  has_many :sectors
	  has_many :sections, through: :sectors
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
	resourcify
end

app/models/cost.rb
class Cost < ApplicationRecord
	belongs_to :project
	resourcify

def day
  self.created_at.strftime("%D")
end

def week
  self.created_at.strftime("%W")
end

end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/dream.rb
class Dream < ApplicationRecord
	resourcify
end

app/models/expertlead.rb
class Expertlead < ApplicationRecord
	resourcify
end

app/models/lead.rb
class Lead < ApplicationRecord
	resourcify
end

app/models/legend.rb
class Legend < ApplicationRecord
	resourcify
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
	attachment :article_image
	belongs_to :article
end

app/models/potential.rb
class Potential < ApplicationRecord
	resourcify
end

app/models/project.rb
class Project < ApplicationRecord
	resourcify
	has_many :costs
	has_many :timelines
	has_many :userprojects, :dependent => :destroy, :autosave => true
    has_many :users, through: :userprojects
    has_many :protypes, :dependent => :destroy, :autosave => true
    has_many :projecttypes, through: :protypes
    accepts_nested_attributes_for :costs, :allow_destroy => true
    default_scope -> { order('created_at DESC') }
end

app/models/protype.rb
class Protype < ApplicationRecord
	belongs_to :project
	belongs_to :projecttype
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/section.rb
class Section < ApplicationRecord
	resourcify
	extend FriendlyId
    friendly_id :name, use: :slugged
	mount_uploader :sectionimage, SectionimageUploader
	has_many :sectors
	has_many :articles, through: :sectors
end

app/models/sector.rb
class Sector < ApplicationRecord
	belongs_to :article
	belongs_to :section
end

app/models/timeline.rb
class Timeline < ApplicationRecord
	resourcify
	belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  after_create :send_admin_mail
  has_many :userprojects, :dependent => :destroy, :autosave => true
  has_many :projects, through: :userprojects

     
  def send_admin_mail
    RegistrationMailer.register_message(self).deliver
  end

end

app/models/web.rb
class Web < ApplicationRecord
	resourcify
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  before_action :set_timeline, only: [:show, :edit, :update, :destroy]
  before_action :set_project
  # GET /timelines
  # GET /timelines.json
  def index
    @timelines = Timeline.all
  end

  # GET /timelines/1
  # GET /timelines/1.json
  def show
  end

  # GET /timelines/new
  def new
    @timeline = @project.timelines.new
  end

  # GET /timelines/1/edit
  def edit
  end

  # POST /timelines
  # POST /timelines.json
  def create
    @timeline = @project.timelines.new(timeline_params)

    respond_to do |format|
      if @timeline.save
        format.html { redirect_to @project }
        format.json { render :show, status: :created, location: @timeline }
      else
        format.html { render :new }
        format.json { render json: @timeline.errors, status: :unprocessable_entity }
      end
    end
    authorize! :create, @timeline
  end

  # PATCH/PUT /timelines/1
  # PATCH/PUT /timelines/1.json
  def update
    respond_to do |format|
      if @timeline.update(timeline_params)
        format.html { redirect_to @timeline, notice: 'Timeline was successfully updated.' }
        format.json { render :show, status: :ok, location: @timeline }
      else
        format.html { render :edit }
        format.json { render json: @timeline.errors, status: :unprocessable_entity }
      end
    end
    authorize! :update, @timeline
  end

  # DELETE /timelines/1
  # DELETE /timelines/1.json
  def destroy
    @timeline.destroy
    respond_to do |format|
      format.html { redirect_to timelines_url, notice: 'Timeline was successfully destroyed.' }
      format.json { head :no_content }
    end
    authorize! :destroy, @timeline
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timeline
      @timeline = Timeline.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timeline_params
      params.require(:timeline).permit(:weareat, :milestone, :description, :timelink, :project_id)
    end
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/views/timelines/_form.html.erb
<div class="container">
  <h1 style="text-align: center;" >New Timeline</h1>
  <div class="row">
    <div class="col-sm-6">
<%= form_for [@project,@timeline] do |f| %>
  <% if timeline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(timeline.errors.count, "error") %> prohibited this timeline from being saved:</h2>

      <ul>
      <% timeline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :weareat %>
    <%= f.text_field :weareat, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :milestone %>
    <%= f.text_field :milestone, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :timelink %>
    <%= f.text_field :timelink, :class => "form-control" %>
  </div>

  

  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

</div>
</div>
</div>

app/views/timelines/_timeline.html.erb
<style type="text/css">
.progresshold{
  background-color: #ffffff;
  border-radius: 10px;
  margin: 15px;
  padding: 20px;
  border: 1px solid #cccccc;
}

</style>

<div class="col-lg-12">
<div class="progresshold">
<h2 style="text-align: left; font-family: 'Poppins', sans-serif;"><%= timeline.milestone %></h2>
<p style="font-weight: 300;"><%= markdown(timeline.weareat) %></h4>
<p style="font-weight: 300;"><%= markdown(timeline.description) %></h4>
<p style="font-weight: 300;"><%= markdown(timeline.timelink) %></h4>
</div>
</div>

app/views/timelines/edit.html.erb
<h1>Editing Timeline</h1>

<%= render 'form', timeline: @timeline %>

<%= link_to 'Show', @timeline %> |
<%= link_to 'Back', timelines_path %>

app/views/timelines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Timelines</h1>

<table>
  <thead>
    <tr>
      <th>Weareat</th>
      <th>Milestone</th>
      <th>Description</th>
      <th>Timelink</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timelines.each do |timeline| %>
      <tr>
        <td><%= timeline.weareat %></td>
        <td><%= timeline.milestone %></td>
        <td><%= timeline.description %></td>
        <td><%= timeline.timelink %></td>
        <td><%= timeline.project_id %></td>
        <td><%= link_to 'Show', timeline %></td>
        <td><%= link_to 'Edit', edit_timeline_path(timeline) %></td>
        <td><%= link_to 'Destroy', timeline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timeline', new_timeline_path %>

app/views/timelines/new.html.erb
<br><br><br>


<%= render 'form', timeline: @timeline %>

<br><br>

app/views/timelines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weareat:</strong>
  <%= @timeline.weareat %>
</p>

<p>
  <strong>Milestone:</strong>
  <%= @timeline.milestone %>
</p>

<p>
  <strong>Description:</strong>
  <%= @timeline.description %>
</p>

<p>
  <strong>Timelink:</strong>
  <%= @timeline.timelink %>
</p>

<p>
  <strong>Project:</strong>
  <%= @timeline.project_id %>
</p>

<%= link_to 'Edit', edit_timeline_path(@timeline) %> |
<%= link_to 'Back', timelines_path %>